import type { Insight } from '../../types';
import { ConfidenceBadge } from '../common/ui';
import { Info } from '../common/icons';

const KIND_ACCENT: Record<Insight['kind'], string> = {
  'content-led-lift': 'var(--strong)',
  'demand-strength': 'var(--moderate)',
  'paid-delivery': 'var(--soft)',
  watch: 'var(--accent)',
  insufficient: 'var(--flat)',
};

export function InsightBanner({ insights, max = 3 }: { insights: Insight[]; max?: number }) {
  const shown = insights.slice(0, max);
  return (
    <div className="card" style={{ padding: 14 }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 7, marginBottom: 10 }}>
        <Info size={14} />
        <span style={{ fontSize: 12.5, fontWeight: 600 }}>Plain-English observations</span>
        <span style={{ fontSize: 11, color: 'var(--text-faint)', marginLeft: 'auto' }}>Generated by deterministic rules · correlation, not attribution</span>
      </div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))', gap: 10 }}>
        {shown.map((ins) => (
          <div key={ins.id} style={{ borderLeft: `3px solid ${KIND_ACCENT[ins.kind]}`, paddingLeft: 11, display: 'flex', flexDirection: 'column', gap: 5 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <span style={{ fontSize: 13, fontWeight: 600 }}>{ins.title}</span>
            </div>
            <p style={{ margin: 0, fontSize: 12.5, color: 'var(--text-muted)', lineHeight: 1.5 }}>{ins.text}</p>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 2 }}>
              <ConfidenceBadge level={ins.confidence} />
              <span style={{ fontSize: 11, color: 'var(--text-faint)' }}>{ins.evidence}</span>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
